# Generated by Django 4.2.1 on 2023-05-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cinemas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("tickets_phone", models.IntegerField()),
                ("city", models.CharField(max_length=30)),
                ("street", models.CharField(max_length=50)),
                ("house", models.PositiveIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name": "Кинотеатор",
                "verbose_name_plural": "Кинотеатры",
            },
        ),
        migrations.CreateModel(
            name="MovieFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("price", models.IntegerField()),
            ],
            options={
                "verbose_name": "Киноформат",
                "verbose_name_plural": "Киноформаты",
            },
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("filmmaker", models.CharField(max_length=60)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("1", "action"),
                            ("2", "comedy"),
                            ("3", "melodrama"),
                            ("4", "drama"),
                            ("5", "horror"),
                            ("6", "fantasy"),
                            ("7", "cartoon"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "age_limit",
                    models.CharField(
                        choices=[
                            ("1", "6+"),
                            ("2", "12+"),
                            ("3", "16+"),
                            ("4", "18+"),
                            ("5", "-"),
                        ],
                        default="5",
                        max_length=4,
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                (
                    "movie_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movieformat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
            },
        ),
        migrations.CreateModel(
            name="Showtimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_session", models.TimeField()),
                ("end_session", models.TimeField()),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.cinemas"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movies"
                    ),
                ),
                (
                    "rooms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сеанс",
                "verbose_name_plural": "Сеансы",
            },
        ),
    ]
