# Generated by Django 4.1.7 on 2023-05-23 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cinemas",
            options={"verbose_name": "Кинотеатор", "verbose_name_plural": "Кинотеатры"},
        ),
        migrations.AlterModelOptions(
            name="movies",
            options={"verbose_name": "Фильм", "verbose_name_plural": "Фильмы"},
        ),
        migrations.AlterModelOptions(
            name="showtimes",
            options={"verbose_name": "Сеанс", "verbose_name_plural": "Сеансы"},
        ),
    ]
