# Generated by Django 4.2.1 on 2023-05-27 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_feedback_clubcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubcard",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
